//页面展示格式
export default [
    {val:'businessNature_Format' ,name:'经营性质'},
    {val:'certificateType_Format',name:'证件类型'},
    {val:'connectMode_Format',name:'场所接入方式'},
    {val:'accessServicecode_Format',name:'接入网路服务商'},
    {val:'netsiteType_Format',name:'上网场所服务类型'},
    {val:'businessState_Format',name:'营业状态'},
    {val:'equipmentType_Format',name:'WIFI采集设备 设备类型'},
    {val:'authType_Format',name:'认证类型'},
    {val:'microprobeType_Format',name:'系统采集类型'},
    {val:'policyType_Format',name:'重点人员布控类型'},
    {val:'analyTargetType_Format',name:'分析对象类型'},
    {val:'analyType_Format',name:'分析任务类型'},
    {val:'taskStatus_Format',name:'分析任务状态'},
    {val:'taskProgress_Format',name:'任务进度'},
    {val:'accountType_Format',name:'虚拟身份类型'},
    {val:'nationType_Format',name:'民族'},
    {val:'alarmType_Format',name:'报警类型'},
    {val:'idBehaviorType_Format',name:'聊天消息接收发送类型'},
    {val:'number2ip',name:'数字转IP格式化'},        
    {val:'timestamp2time',name:'时间戳转标准时间'},
    {val:'region_Format',name:'地区编码转地区名称'},
    {val:'security_soft_ware_org_Format',name:'厂商编码转厂商名称'},
    {val:'sourceType_Format',name:'数据源类型'},
    {val:'police_Format',name:'派出所编码转派出所名称'},
    {val:'site_Format',name:'场所编码转场所名称'},
    {val:'encryptionType_Format',name:'WIFI设备加密类型'},
    {val:'siteAddress_Format',name:'场所编码转场所地址'},
    {val:'behavior_note_Format',name:'聊天消息接收发送说明'},
    {val:'policyType_Format',name:'重点人员布控类型'},
    {val:'crimeMatchMode_Format',name:'在逃人员匹配模式'}
]
